# Generated by Django 4.2.9 on 2026-03-01 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Sana')),
                ('time', models.TimeField(verbose_name='Vaqt')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (daqiqa)')),
                ('status', models.CharField(choices=[('pending', '⏳ Kutilmoqda'), ('confirmed', '✅ Tasdiqlangan'), ('cancelled', '❌ Bekor qilingan'), ('completed', '✔️ Tugallangan'), ('no_show', '👻 Kelmadi'), ('rescheduled', "🔄 Ko'chirilgan")], default='pending', max_length=20, verbose_name='Status')),
                ('complaint', models.TextField(blank=True, verbose_name='Shikoyat')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Narxi (so'm)")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langanmi?")),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram xabar ID')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('patient', 'Bemor'), ('clinic', 'Klinika'), ('system', 'Tizim')], max_length=20)),
            ],
            options={
                'verbose_name': 'Navbat',
                'verbose_name_plural': 'Navbatlar',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
