# Generated by Django 4.2.9 on 2026-03-01 15:02

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Klinika nomi')),
                ('name_uz', models.CharField(blank=True, max_length=255, verbose_name="O'zbekcha nomi")),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('city', models.CharField(default='Toshkent', max_length=100, verbose_name='Shahar')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clinic_type', models.CharField(choices=[('general', '🏥 Umumiy'), ('dental', '🦷 Stomatologiya'), ('eye', "👁 Ko'z klinikasi"), ('skin', '🧴 Teri klinikasi'), ('neuro', '🧠 Nevrologiya'), ('cardio', '❤️ Kardiologiya'), ('child', '👶 Bolalar klinikasi'), ('other', '🏨 Boshqa')], default='general', max_length=20, verbose_name='Klinika turi')),
                ('plan', models.CharField(choices=[('trial', '🔓 Sinov (bepul)'), ('free', '🆓 Bepul'), ('starter', '⭐ Starter ($20/oy)'), ('pro', '💎 Pro ($40/oy)'), ('enterprise', '🏆 Enterprise ($80/oy)')], default='trial', max_length=20, verbose_name='Tarif')),
                ('status', models.CharField(choices=[('active', '✅ Faol'), ('inactive', '⏸ Nofaol'), ('suspended', "🚫 To'xtatilgan"), ('trial', '🔓 Sinov rejimi')], default='trial', max_length=20, verbose_name='Status')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinov muddati')),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Obuna muddati')),
                ('work_start', models.TimeField(default='08:00', verbose_name='Ish boshlanishi')),
                ('work_end', models.TimeField(default='18:00', verbose_name='Ish tugashi')),
                ('lunch_start', models.TimeField(blank=True, null=True, verbose_name='Tushlik boshlanishi')),
                ('lunch_end', models.TimeField(blank=True, null=True, verbose_name='Tushlik tugashi')),
                ('appointment_duration', models.PositiveIntegerField(default=30, verbose_name='Navbat davomiyligi (daqiqa)')),
                ('working_days', models.JSONField(default=list, help_text='["monday","tuesday","wednesday","thursday","friday"]', verbose_name='Ish kunlari')),
                ('total_appointments', models.PositiveIntegerField(default=0)),
                ('total_patients', models.PositiveIntegerField(default=0)),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_clinics', to=settings.AUTH_USER_MODEL, verbose_name='Adminlar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_clinics', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Klinika',
                'verbose_name_plural': 'Klinikalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Xizmat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Narxi (so'm)")),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Rang')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic', verbose_name='Klinika')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicInviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taklif tokeni',
                'verbose_name_plural': 'Taklif tokenlari',
            },
        ),
    ]
