# Generated by Django 4.2.9 on 2026-03-01 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='clinic_covers/', verbose_name='Cover rasm'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='deep_link_token',
            field=models.CharField(blank=True, help_text='t.me/CLinksBot?start=clinic_TOKEN', max_length=32, unique=True, verbose_name='Bot Deep Link Token'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured?'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan?'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Reyting'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='plan',
            field=models.CharField(choices=[('trial', '🔓 Sinov (bepul, 30 kun)'), ('starter', '⭐ Starter ($19/oy)'), ('pro', '💎 Pro ($39/oy)'), ('business', '🚀 Business ($79/oy)'), ('enterprise', '🏆 Enterprise (Custom)')], default='trial', max_length=20, verbose_name='Tarif'),
        ),
        migrations.CreateModel(
            name='ClinicReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Bemor ismi')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], verbose_name='Reyting')),
                ('comment', models.TextField(blank=True, verbose_name='Sharh')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Tasdiqlangan?')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinics.clinic', verbose_name='Klinika')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
                'unique_together': {('clinic', 'telegram_id')},
            },
        ),
    ]
