# Generated by Django 4.2.9 on 2026-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_cover_image_clinic_deep_link_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='plan',
            field=models.CharField(choices=[('trial', '🔓 Sinov (bepul, 30 kun)'), ('free', '🆓 Lite (Bepul)'), ('starter', '⭐ Starter ($19/oy)'), ('pro', '💎 Pro ($39/oy)'), ('business', '🚀 Business ($79/oy)'), ('enterprise', '🏆 Enterprise (Custom)')], default='trial', max_length=20, verbose_name='Tarif'),
        ),
    ]
