# Generated by Django 4.2.9 on 2026-03-01 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField()),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('content', models.TextField()),
                ('direction', models.CharField(choices=[('in', 'Kiruvchi'), ('out', 'Chiquvchi')], default='out', max_length=10)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(default='uz', max_length=5)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('state_data', models.JSONField(default=dict)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchisi',
                'verbose_name_plural': 'Bot foydalanuvchilari',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Bot token')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Bot username')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Bot nomi')),
                ('webhook_url', models.URLField(blank=True)),
                ('is_webhook_set', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('welcome_message', models.TextField(default="Assalomu alaykum! {clinic_name} klinikasiga xush kelibsiz! 🏥\n\nNavbat olish uchun /start buyrug'ini yuboring.", verbose_name='Xush kelibsiz xabari')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский')], default='uz', max_length=5, verbose_name='Til')),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_appointments_via_bot', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Botlar',
            },
        ),
    ]
