# Generated by Django 4.2.9 on 2026-03-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('patients', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bot', to='clinics.clinic', verbose_name='Klinika'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_users', to='bots.telegrambot', verbose_name='Bot'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.telegrambot'),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='bot_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.botuser'),
        ),
        migrations.AlterUniqueTogether(
            name='botuser',
            unique_together={('bot', 'telegram_id')},
        ),
    ]
