# Generated by Django 4.2.9 on 2026-03-01 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', '👨 Erkak'), ('female', '👩 Ayol'), ('unknown', "❓ Noma'lum")], default='unknown', max_length=10, verbose_name='Jins')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Qon guruhi')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergiyalar')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='Surunkali kasalliklar')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic', verbose_name='Klinika')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'ordering': ['-created_at'],
                'unique_together': {('clinic', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaints', models.TextField(verbose_name='Shikoyatlar')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Tashxis')),
                ('treatment', models.TextField(blank=True, verbose_name='Davolash')),
                ('prescription', models.TextField(blank=True, verbose_name='Retsept')),
                ('next_visit', models.DateField(blank=True, null=True, verbose_name='Keyingi tashrif')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Jami summa (so'm)")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan summa")),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='appointments.appointment', verbose_name='Navbat')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='doctors.doctor', verbose_name='Shifokor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Tibbiy yozuv',
                'verbose_name_plural': 'Tibbiy yozuvlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
