# Generated by Django 4.2.9 on 2026-03-01 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPatient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('telegram_first_name', models.CharField(blank=True, max_length=100, verbose_name='Telegram ism')),
                ('telegram_last_name', models.CharField(blank=True, max_length=100, verbose_name='Telegram familiya')),
                ('telegram_language', models.CharField(default='uz', max_length=10, verbose_name='Til sozlamasi')),
                ('telegram_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon (Telegramdan)')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', '👨 Erkak'), ('female', '👩 Ayol'), ('unknown', '❓ Nomalum')], default='unknown', max_length=10, verbose_name='Jins')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan?')),
                ('is_registered', models.BooleanField(default=False, verbose_name="Profil to'ldirilgan?")),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('total_appointments', models.PositiveIntegerField(default=0, verbose_name='Jami navbatlar')),
                ('total_clinics_visited', models.PositiveIntegerField(default=0, verbose_name='Tashrif etgan klinikalar')),
            ],
            options={
                'verbose_name': 'Bemor (Global)',
                'verbose_name_plural': 'Bemorlar (Global)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='telegram_username',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', '👨 Erkak'), ('female', '👩 Ayol'), ('unknown', '❓ Nomalum')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='global_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_records', to='patients.globalpatient', verbose_name='Global bemor'),
        ),
    ]
