# Generated by Django 4.2.9 on 2026-03-01 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/', verbose_name='Foto')),
                ('specialty', models.CharField(max_length=255, verbose_name='Mutaxassislik')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('bio', models.TextField(blank=True, verbose_name='Haqida')),
                ('education', models.TextField(blank=True, verbose_name="Ta'lim")),
                ('achievements', models.TextField(blank=True, verbose_name='Yutuqlar')),
                ('consultation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Konsultatsiya narxi (so'm)")),
                ('custom_schedule', models.BooleanField(default=False, verbose_name='Alohida jadval?')),
                ('work_start', models.TimeField(blank=True, null=True)),
                ('work_end', models.TimeField(blank=True, null=True)),
                ('working_days', models.JSONField(blank=True, null=True, verbose_name='Ish kunlari (alohida)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('total_appointments', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic', verbose_name='Klinika')),
                ('services', models.ManyToManyField(blank=True, related_name='doctors', to='clinics.clinicservice', verbose_name='Xizmatlar')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_working', models.BooleanField(default=False)),
                ('work_start', models.TimeField(blank=True, null=True)),
                ('work_end', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Jadval istisnosi',
                'verbose_name_plural': 'Jadval istisno',
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
