# Generated by Django 4.2.9 on 2026-03-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='middle_name',
        ),
    ]
